CREATE TABLE IF NOT EXISTS admins (
  email TEXT PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS tenants (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  unit_label TEXT,
  rent_amount_cents INTEGER NOT NULL,
  due_day INTEGER NOT NULL CHECK (due_day BETWEEN 1 AND 28),
  late_fee_cents INTEGER NOT NULL DEFAULT 0,
  late_fee_after_day INTEGER,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS payments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tenant_id INTEGER NOT NULL REFERENCES tenants(id),
  amount_cents INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  period_label TEXT,
  -- Breakdown of amount_cents, captured at charge-creation time so the
  -- PDF receipt (src/lib/pdf.js) can itemize rent vs. late fee instead of
  -- showing one lump sum. NULL on payments created before these columns
  -- existed -- the receipt falls back to a single "Rent" line for those.
  -- One-time fees aren't duplicated here; they're reconstructed from
  -- tenant_fees.applied_payment_id instead, which already works for
  -- payments old and new.
  rent_amount_cents INTEGER,
  late_fee_cents INTEGER,
  -- 'stripe' for a payment made through this app's Stripe Checkout;
  -- 'direct' for one collected outside the app (cash, check, handed
  -- directly to the landlord) and recorded here after the fact.
  method TEXT NOT NULL DEFAULT 'stripe',
  stripe_checkout_session_id TEXT UNIQUE,
  stripe_payment_intent_id TEXT,
  -- Stripe's own hosted receipt page for a succeeded card/bank charge --
  -- set from the webhook once payment succeeds; NULL until then, and for
  -- 'direct' (non-Stripe) payments. Kept for reference only; the actual
  -- "View / download" link in the app and the confirmation email use a
  -- PDF generated by this app itself instead (src/lib/pdf.js), since
  -- Stripe's page doesn't offer a real PDF download for a plain charge.
  receipt_url TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  paid_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_payments_tenant ON payments(tenant_id);

-- Makes the webhook's `INSERT OR IGNORE ... stripe_payment_intent_id`
-- (src/index.js, handleStripeWebhook) safe against Stripe redelivering
-- the same payment_intent.succeeded event -- a partial index so 'direct'
-- payments (NULL here) never collide with each other.
CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_stripe_intent_unique
  ON payments(stripe_payment_intent_id) WHERE stripe_payment_intent_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS maintenance_requests (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tenant_id INTEGER NOT NULL REFERENCES tenants(id),
  -- Free-text category the tenant picks from a fixed dropdown on the
  -- form (Plumbing, Electrical, etc.) -- not constrained here so the
  -- dropdown's options can change without a migration.
  issue_type TEXT,
  -- Tenant-reported date the issue started (YYYY-MM-DD, from an HTML
  -- date input). Optional -- not always known -- and stored as a plain
  -- label, never used in date math.
  issue_started_on TEXT,
  description TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_maintenance_tenant ON maintenance_requests(tenant_id);

-- One-time email magic-link tokens. `subject` is a tenant's numeric id
-- (as text) when subject_type='tenant', or an admin's email when
-- subject_type='admin' (admins have no numeric id). used_at prevents a
-- link from being redeemed twice, even before it expires.
CREATE TABLE IF NOT EXISTS login_tokens (
  token TEXT PRIMARY KEY NOT NULL,
  subject_type TEXT NOT NULL CHECK (subject_type IN ('tenant', 'admin')),
  subject TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_login_tokens_expires ON login_tokens(expires_at);

-- One-time fees an admin adds for a tenant (a custom label + amount --
-- distinct from the recurring late fee on `tenants`, which fires
-- automatically past a day-of-month cutoff). A 'pending' fee is added to
-- the total on the tenant's *next* Stripe payment, then flipped to
-- 'applied' once that payment succeeds -- it's never added twice, and
-- never rewrites amounts already on a `payments` row.
CREATE TABLE IF NOT EXISTS tenant_fees (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tenant_id INTEGER NOT NULL REFERENCES tenants(id),
  label TEXT NOT NULL,
  amount_cents INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'applied')),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  applied_at TEXT,
  applied_payment_id INTEGER REFERENCES payments(id)
);

CREATE INDEX IF NOT EXISTS idx_tenant_fees_tenant ON tenant_fees(tenant_id, status);
